### ISSUE TITLE
[GENERAL] AI does not work!

### ISSUE THREAD

**Issue by Aroliacue** [VoRe-ss13/ss13#98]
#### Brief description of the bug
The AI just seems to not work at all. It cannot access any of the subsystems, cannot view cameras, cannot move its 'eye' around, cannot direct control its AI cyborgs and is just overall nonfunctional.

#### What you expected to happen
The AI to be able to do stuff

#### What actually happened
The AI cannot do stuff

#### Steps to reproduce
- Join as AI
- Observe as AI does not work

#### Code Revision
Server revision: B:-Using TGS- D:-Using TGS-
Commit: GLOB.revdata.revision
TGS version: 6.1.5
DMAPI version: 5.8.0
The following pull requests are currently test merged:
[#52: 'Swaps map to NLS Forbearance (relicbase.dm)' by purplefoxy27 at commit bb4e784783](http://127.0.0.1:49341/pull/52)
 

#### Anything else you may wish to add:
Seems to be working fine on Chompstation live, so it's potentially a map issue (AI isn't hooked up to the map's network, maybe?)

**Comment by LucasRo7** [comment]
I managed to reproduce this issue while hosting locally by deleting the file `config/names/ai.txt`, no announcement, no cameras, no eye just as what happens on the server(and described on the issue)
@cadyn might be worth checking if that file was deleted
